/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadgrupo25.Vistas;

import java.beans.PropertyVetoException;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import universidadgrupo25.Entidades.Alumno;
import universidadgrupo25.Entidades.Materia;
import universidadgrupo25.accesoADatos.InscripcionData;
import universidadgrupo25.accesoADatos.MateriaData;
/**
 *
 * @author Ramirez
 */
public class AlumnoPorMat extends javax.swing.JInternalFrame {

    MateriaData matdata = new MateriaData();
    InscripcionData inscdata = new InscripcionData();
    private DefaultTableModel modelo= new DefaultTableModel();
    List<Materia> lista = matdata.listarMaterias();
    /**
     * Creates new form AlumnoPorMat
     */
    
    public AlumnoPorMat() {
        initComponents();
        armarCabecera();
        mostarMateria();
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCBListaMateria = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtAlumnoporMateria = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Listado de Alumnos por Materia");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Seleccione una Materia");

        jCBListaMateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        jCBListaMateria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCBListaMateriaMouseClicked(evt);
            }
        });
        jCBListaMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBListaMateriaActionPerformed(evt);
            }
        });

        jtAlumnoporMateria.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jtAlumnoporMateria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtAlumnoporMateria);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCBListaMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBListaMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBListaMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBListaMateriaActionPerformed
         borrarFilas();
         if(jCBListaMateria.getSelectedItem().toString() == "-"){
             return;
         }else{
             
         int opcion = jCBListaMateria.getSelectedIndex();
         
         Materia materia = lista.get(opcion-1);
         
             cargarAlumnoXMateria(materia);
             System.out.println(materia);
         }
            
        
    }//GEN-LAST:event_jCBListaMateriaActionPerformed

    private void jCBListaMateriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBListaMateriaMouseClicked
        // TODO add your handling code here:                                         
    }//GEN-LAST:event_jCBListaMateriaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            this.setClosed(true);
        } catch (PropertyVetoException ex) {
            JOptionPane.showMessageDialog(this, "Error salir");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCBListaMateria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtAlumnoporMateria;
    // End of variables declaration//GEN-END:variables

private void armarCabecera(){
   modelo.addColumn("ID");
   modelo.addColumn("D.N.I");
   modelo.addColumn("Apellido");
   modelo.addColumn("Nombre");
   jtAlumnoporMateria.setModel(modelo);
   
    
}

    private void mostarMateria() {
        
        
        //jCBListaMateria.addItem("seleccionar");
        for (int i=0;i<lista.size(); i++){
            jCBListaMateria.addItem(lista.get(i).getNombre());
    }
    }
    
    private void cargarAlumnoXMateria (Materia idMateria){
        System.out.println(idMateria.getIdMateria());
        List<Alumno> lista = inscdata.obtenerAlumnoPorMateria(idMateria.getIdMateria());
        modelo = (DefaultTableModel)jtAlumnoporMateria.getModel();
        
        for (Alumno al : lista) {
            if(idMateria.getNombre() == jCBListaMateria.getSelectedItem()){

                    modelo.addRow(new Object[]{al.getIdAlumno(), al.getDni(), al.getNombre(), al.getApellido()});
                }
        }
        
//            Object[] row = new Object[3];
//            for (int i = 0; i < lista.size();i++) {
//            row[0]= lista.get(i).getIdAlumno();
//            row[1]= lista.get(i).getDni();
//            row[2]= lista.get(i).getNombre();
//            row[3]= lista.get(i).getApellido();
//            
//            modelo.addRow(row);
            
    }
        private void borrarFilas(){
            int filas = modelo.getRowCount() - 1;
        
            for (int f = filas; f >= 0; f--) {
                modelo.removeRow(f);
        }
    }
    }
        
  
    
       







